version: "3.9"

# TODO: Remove unused ports
services:
  airflow:
    build:
      context: .
      dockerfile: airflow.dockerfile
    image: felixhoffmnn/airflow:latest
    container_name: airflow
    volumes:
      - ./big_data/dags:/home/airflow/airflow/dags/
      - ./big_data/python:/home/airflow/airflow/python/
      - ./big_data/plugins:/home/airflow/airflow/plugins/
      - ./data/kaggle:/home/airflow/.kaggle/
      - ./data/output:/home/airflow/output/
    ports:
      - 8080:8080
    networks:
      - bigdatanet

  spark:
    image: marcelmittelstaedt/spark_base:latest
    container_name: hadoop
    ports:
      - 8088:8088
      - 9870:9870
      - 9864:9864
      - 8888:8888
    networks:
      - bigdatanet

networks:
  bigdatanet:
    name: bigdatanet
    driver: bridge
